vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: assets/images/articles
            upload_destination: '%kernel.project_dir%/public/assets/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
