controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_admin_reported_comments:
    path: '/admin/reported-comments'
    controller: 'App\Controller\Admin\CommentCrudController::showReportedComments'

app_admin_unreport_comment:
    path: '/admin/comment/unreport/{id}'
    controller: 'App\Controller\Admin\CommentCrudController::unreport'
    methods: ['GET']
